### ISSUE TITLE
A better folder structure and filename pattern

### ISSUE THREAD

**Issue by ntsd** [narze/ratchagitja.md#23]
Now we get the filename too long problem in Linux and Windows and the file is not grouping or cataloged.

Expectation:
1. design a clean project structure -can be grouped by `ประเภท`, 'เล่ม', 'ตอน'
2. define a file name pattern - do not recommend Thai characters, these can be the original pdf file name but change the extension to `.md`

can check this CSV for the header we have https://raw.githubusercontent.com/narze/ratchagitja.md/main/data/ratchakitcha.csv

**Comment by narze** [comment]
I'm thinking about using original pdf name e.g. `140D050S0000000004300.pdf` is all good, since if we have some kind of website we don't care what the file name is anyway

**Comment by QuAzZeR** [comment]
I think the folder structure can be `year`/`month` or `เล่ม`/`ตอน`, but I'm not sure which one is better to use in the future. Are they focusing on `เล่ม` and `ตอน` or `year` and `month`
P.S. `year` and `month` are from the announcement date.

**Comment by narze** [comment]
เดี๋ยวจะทำเป็น flat ก่อนนะครับ ทุกอย่างจะอยู่ใน `entries` (บนเว็บจะแบ่งโดยการใช้ metadata) เมื่อมีข้อมูลมากพอจะทำ folder ครับ
เหตุผลคือเดี๋ยวจะย้ายกันไปมาไม่สะดวกแล้วจะเกิด conflicts เยอะ

**Comment by ntsd** [comment]
We are using `entries /category/volume/section/id.md` for now
