### ISSUE TITLE
Filter categories

### ISSUE THREAD

**Issue by ntsd** [narze/ratchagitja.md#46]
We don't need all the categories here, but not sure what are the important ones.

**Comment by Thanyanit-J** [comment]
For starter, categories like หมวด ก ข ค ง ง(พิเศษ) probably fine as an MVP.

Then, we may want to categorize according to the purpose of each document, such as:
- ประกาศใช้กฎหมาย
- ประกาศคำสั่ง (แต่งตั้งยศ อนุมัติโครงการ แต่งตั้งสภา ฯลฯ)
- ประกาศทั่วไป
- แก้เอกสาร แก้คำผิด
- กระทู้สนทนา (for real, seriously)

For the law announcement, we can further categorize as:
- รัฐธรรมนูญ
- พระราชบัญญัติ
- กฎกระทรวง
- ฯลฯ

**Comment by ntsd** [comment]
> For starter, categories like หมวด ก ข ค ง ง(พิเศษ) probably fine as an MVP.
> 
> Then, we may want to categorize according to the purpose of each document, such as:
> 
> * ประกาศใช้กฎหมาย
> * ประกาศคำสั่ง (แต่งตั้งยศ อนุมัติโครงการ แต่งตั้งสภา ฯลฯ)
> * ประกาศทั่วไป
> * แก้เอกสาร แก้คำผิด
> * กระทู้สนทนา (for real, seriously)
> 
> For the law announcement, we can further categorize as:
> 
> * รัฐธรรมนูญ
> * พระราชบัญญัติ
> * กฎกระทรวง
> * ฯลฯ

Thank you for the information. I made a filter list here https://github.com/narze/ratchagitja.md/blob/main/data/filter.json. 
And data visualization for it https://github.com/narze/ratchagitja.md/blob/main/data/visualize.ipynb
